### ISSUE TITLE
microservicebus module start in wrong directory in docs

### ISSUE THREAD

**Issue by Triamus** [axians/microservicebus-tutorial#2]
I followed tutorial [Getting started: Build your first solution](https://github.com/axians/microservicebus-tutorial/blob/master/GettingStarted.md) and in point `4` it says

```
cd node_modules/microservicebus.node
```

However, this directory does not exist. Rather, I found

```
cd node_modules/microservicebus-node
```

**Comment by stefannilsson** [comment]
Thank you @Triamus for the report! It looks like @wmmihaa corrected this instantly. I'm closing the issue.
